import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-screen flex justify-center items-center">
        {children}
    </main>
  );
}
